package com.hrms.dto;
// Generated Nov 18, 2016 10:25:48 AM by Hibernate Tools 4.3.1


import com.hrms.model.EmployeeProfile;
import com.hrms.model.LoansMaster;
import java.util.Date;

/**
 * LoanAllotment generated by hbm2java
 */
public class Loan implements java.io.Serializable {


     private Integer id;
     private EmployeeProfile employeeProfile;
     private LoansMaster loansMaster;
     private String loanType;
     private Integer requestedAmt;
     private Integer sanctionedAmt;
     private String status;
     private Date loanApprovalDate;
     private Date loanCreationDate;
     private String householdThings;
     private int empId;
     private int loanId;
     private String loanApprovaldate;
      private String loanCreationdate;
       private Integer gasLoan;
     private Integer traLoan;
     private Integer cashLoan;

    public Loan() {
    }

    public Loan(EmployeeProfile employeeProfile,Integer gasLoan,Integer traLoan,Integer cashLoan, LoansMaster loansMaster, String loanType, Integer requestedAmt, Integer sanctionedAmt, String status, Date loanApprovalDate, Date loanCreationDate, String householdThings) {
       this.employeeProfile = employeeProfile;
       this.loansMaster = loansMaster;
       this.loanType = loanType;
       this.requestedAmt = requestedAmt;
       this.sanctionedAmt = sanctionedAmt;
       this.status = status;
       this.loanApprovalDate = loanApprovalDate;
       this.householdThings = householdThings;
       this.loanCreationDate=loanCreationDate;
       this.cashLoan=cashLoan;
       this.traLoan=traLoan;
       this.gasLoan=gasLoan;
    }

    public Integer getGasLoan() {
        return gasLoan;
    }

    public void setGasLoan(Integer gasLoan) {
        this.gasLoan = gasLoan;
    }

    public Integer getTraLoan() {
        return traLoan;
    }

    public void setTraLoan(Integer traLoan) {
        this.traLoan = traLoan;
    }

    public Integer getCashLoan() {
        return cashLoan;
    }

    public void setCashLoan(Integer cashLoan) {
        this.cashLoan = cashLoan;
    }
    
    public Date getLoanCreationDate() {
        return loanCreationDate;
    }

    public void setLoanCreationDate(Date loanCreationDate) {
        this.loanCreationDate = loanCreationDate;
    }

    public String getLoanCreationdate() {
        return loanCreationdate;
    }

    public void setLoanCreationdate(String loanCreationdate) {
        this.loanCreationdate = loanCreationdate;
    }
    

    public String getLoanApprovaldate() {
        return loanApprovaldate;
    }

    public void setLoanApprovaldate(String loanApprovaldate) {
        this.loanApprovaldate = loanApprovaldate;
    }

    public int getLoanId() {
        return loanId;
    }

    public void setLoanId(int loanId) {
        this.loanId = loanId;
    }
    

    public int getEmpId() {
        return empId;
    }

    public void setEmpId(int empId) {
        this.empId = empId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfile;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfile = employeeProfile;
    }
    public LoansMaster getLoansMaster() {
        return this.loansMaster;
    }
    
    public void setLoansMaster(LoansMaster loansMaster) {
        this.loansMaster = loansMaster;
    }
    public String getLoanType() {
        return this.loanType;
    }
    
    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }
    public Integer getRequestedAmt() {
        return this.requestedAmt;
    }
    
    public void setRequestedAmt(Integer requestedAmt) {
        this.requestedAmt = requestedAmt;
    }
    public Integer getSanctionedAmt() {
        return this.sanctionedAmt;
    }
    
    public void setSanctionedAmt(Integer sanctionedAmt) {
        this.sanctionedAmt = sanctionedAmt;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getLoanApprovalDate() {
        return this.loanApprovalDate;
    }
    
    public void setLoanApprovalDate(Date loanApprovalDate) {
        this.loanApprovalDate = loanApprovalDate;
    }
    public String getHouseholdThings() {
        return this.householdThings;
    }
    
    public void setHouseholdThings(String householdThings) {
        this.householdThings = householdThings;
    }


}


