package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeductionMaster generated by hbm2java
 */
public class DeductionMaster  implements java.io.Serializable {


     private Integer id;
     private EmployeeProfile employeeProfileByEmpdId;
     private Departments deptdId;

    public EmployeeProfile getEmployeeProfileByEmpdId() {
        return employeeProfileByEmpdId;
    }

    public void setEmployeeProfileByEmpdId(EmployeeProfile employeeProfileByEmpdId) {
        this.employeeProfileByEmpdId = employeeProfileByEmpdId;
    }

    public Departments getDeptdId() {
        return deptdId;
    }

    public void setDeptdId(Departments deptdId) {
        this.deptdId = deptdId;
    }
     private int deductionId;
     private String deductionName;
     private String deductionCode;
     private Integer pf;
     private Integer pfNo;
     private Integer ppp;
     private Integer salaryAdvance;
     private Integer totalSanctionedAmount;
     private Integer power;
     private Integer meals;
     private Integer tiffin;
     private Integer tea;
     private Integer store;
     private Integer medicines;
     private Integer cable;
     private Integer gas;
     private Integer adv2;
     private Integer eggs;
     private Integer uniform;
     private Integer totalDeductions;
     private Date ddate;

    public DeductionMaster() {
    }

	
    public DeductionMaster(int deductionId) {
        this.deductionId = deductionId;
    }
    public DeductionMaster(EmployeeProfile employeeProfile, int deductionId, String deductionName, String deductionCode, Integer pf, Integer pfNo, Integer ppp, Integer salaryAdvance, Integer totalSanctionedAmount, Integer power, Integer meals, Integer tiffin, Integer tea, Integer store, Integer medicines, Integer cable, Integer gas, Integer adv2, Integer eggs, Integer uniform, Integer totalDeductions, Date ddate) {
       this.employeeProfileByEmpdId = employeeProfile;
       this.deductionId = deductionId;
       this.deductionName = deductionName;
       this.deductionCode = deductionCode;
       this.pf = pf;
       this.pfNo = pfNo;
       this.ppp = ppp;
       this.salaryAdvance = salaryAdvance;
       this.totalSanctionedAmount = totalSanctionedAmount;
       this.power = power;
       this.meals = meals;
       this.tiffin = tiffin;
       this.tea = tea;
       this.store = store;
       this.medicines = medicines;
       this.cable = cable;
       this.gas = gas;
       this.adv2 = adv2;
       this.eggs = eggs;
       this.uniform = uniform;
       this.totalDeductions = totalDeductions;
       this.ddate = ddate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfileByEmpdId;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfileByEmpdId = employeeProfile;
    }
    public int getDeductionId() {
        return this.deductionId;
    }
    
    public void setDeductionId(int deductionId) {
        this.deductionId = deductionId;
    }
    public String getDeductionName() {
        return this.deductionName;
    }
    
    public void setDeductionName(String deductionName) {
        this.deductionName = deductionName;
    }
    public String getDeductionCode() {
        return this.deductionCode;
    }
    
    public void setDeductionCode(String deductionCode) {
        this.deductionCode = deductionCode;
    }
    public Integer getPf() {
        return this.pf;
    }
    
    public void setPf(Integer pf) {
        this.pf = pf;
    }
    public Integer getPfNo() {
        return this.pfNo;
    }
    
    public void setPfNo(Integer pfNo) {
        this.pfNo = pfNo;
    }
    public Integer getPpp() {
        return this.ppp;
    }
    
    public void setPpp(Integer ppp) {
        this.ppp = ppp;
    }
    public Integer getSalaryAdvance() {
        return this.salaryAdvance;
    }
    
    public void setSalaryAdvance(Integer salaryAdvance) {
        this.salaryAdvance = salaryAdvance;
    }
    public Integer getTotalSanctionedAmount() {
        return this.totalSanctionedAmount;
    }
    
    public void setTotalSanctionedAmount(Integer totalSanctionedAmount) {
        this.totalSanctionedAmount = totalSanctionedAmount;
    }
    public Integer getPower() {
        return this.power;
    }
    
    public void setPower(Integer power) {
        this.power = power;
    }
    public Integer getMeals() {
        return this.meals;
    }
    
    public void setMeals(Integer meals) {
        this.meals = meals;
    }
    public Integer getTiffin() {
        return this.tiffin;
    }
    
    public void setTiffin(Integer tiffin) {
        this.tiffin = tiffin;
    }
    public Integer getTea() {
        return this.tea;
    }
    
    public void setTea(Integer tea) {
        this.tea = tea;
    }
    public Integer getStore() {
        return this.store;
    }
    
    public void setStore(Integer store) {
        this.store = store;
    }
    public Integer getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Integer medicines) {
        this.medicines = medicines;
    }
    public Integer getCable() {
        return this.cable;
    }
    
    public void setCable(Integer cable) {
        this.cable = cable;
    }
    public Integer getGas() {
        return this.gas;
    }
    
    public void setGas(Integer gas) {
        this.gas = gas;
    }
    public Integer getAdv2() {
        return this.adv2;
    }
    
    public void setAdv2(Integer adv2) {
        this.adv2 = adv2;
    }
    public Integer getEggs() {
        return this.eggs;
    }
    
    public void setEggs(Integer eggs) {
        this.eggs = eggs;
    }
    public Integer getUniform() {
        return this.uniform;
    }
    
    public void setUniform(Integer uniform) {
        this.uniform = uniform;
    }
    public Integer getTotalDeductions() {
        return this.totalDeductions;
    }
    
    public void setTotalDeductions(Integer totalDeductions) {
        this.totalDeductions = totalDeductions;
    }
    public Date getDdate() {
        return this.ddate;
    }
    
    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }




}


