package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1



/**
 * Dependents generated by hbm2java
 */
public class Dependents  implements java.io.Serializable {


     private int familyHeadId;
     private FamilyIdentity familyIdentity;

    public Dependents() {
    }

    public Dependents(FamilyIdentity familyIdentity) {
       this.familyIdentity = familyIdentity;
    }
   
    public int getFamilyHeadId() {
        return this.familyHeadId;
    }
    
    public void setFamilyHeadId(int familyHeadId) {
        this.familyHeadId = familyHeadId;
    }
    public FamilyIdentity getFamilyIdentity() {
        return this.familyIdentity;
    }
    
    public void setFamilyIdentity(FamilyIdentity familyIdentity) {
        this.familyIdentity = familyIdentity;
    }




}


