package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeProfile generated by hbm2java
 */
public class EmployeeProfile  implements java.io.Serializable {


     private int empId;
     private Departments departments;
     private EmployeeType employeeType;
     private Date doj;
     private String empName;
     private String gender;
     private Date dob;
     private String aadharNumber;
     private String maritialStatus;
     private String address;
     private String quarterType;
     private String perminentAddress;
     private String selfContactNumber;
     private String emergencyContactNumber;
     private String otEligibility;
     private String proofType;
     private String proofNumber;
     private byte[] proofScannedCopy;
     private String empGrade;
     private Date recordCreationDate;
     private String status;
     private Set leaveMasters = new HashSet(0);
     private Set overtimes = new HashSet(0);
     private Set gasAllotments = new HashSet(0);
     private Set loanAllotments = new HashSet(0);
     private Set incentiveses = new HashSet(0);
     private Set wageses = new HashSet(0);
     private Set deductionMasters = new HashSet(0);
     private Set familyIdentities = new HashSet(0);
     private Set quarterAllotments = new HashSet(0);

    public EmployeeProfile() {
    }

    public EmployeeProfile(int empId) {
        this.empId = empId;
    }

	
    public EmployeeProfile(int empId, String empName) {
        this.empId = empId;
        this.empName = empName;
    }
    public EmployeeProfile(int empId, Departments departments, EmployeeType employeeType, Date doj, String empName, String gender, Date dob, String aadharNumber, String maritialStatus, String address, String quarterType, String perminentAddress, String selfContactNumber, String emergencyContactNumber, String otEligibility, String proofType, String proofNumber, byte[] proofScannedCopy, String empGrade, Date recordCreationDate, String status, Set leaveMasters, Set overtimes, Set gasAllotments, Set loanAllotments, Set incentiveses, Set wageses, Set deductionMasters, Set familyIdentities, Set quarterAllotments) {
       this.empId = empId;
       this.departments = departments;
       this.employeeType = employeeType;
       this.doj = doj;
       this.empName = empName;
       this.gender = gender;
       this.dob = dob;
       this.aadharNumber = aadharNumber;
       this.maritialStatus = maritialStatus;
       this.address = address;
       this.quarterType = quarterType;
       this.perminentAddress = perminentAddress;
       this.selfContactNumber = selfContactNumber;
       this.emergencyContactNumber = emergencyContactNumber;
       this.otEligibility = otEligibility;
       this.proofType = proofType;
       this.proofNumber = proofNumber;
       this.proofScannedCopy = proofScannedCopy;
       this.empGrade = empGrade;
       this.recordCreationDate = recordCreationDate;
       this.status = status;
       this.leaveMasters = leaveMasters;
       this.overtimes = overtimes;
       this.gasAllotments = gasAllotments;
       this.loanAllotments = loanAllotments;
       this.incentiveses = incentiveses;
       this.wageses = wageses;
       this.deductionMasters = deductionMasters;
       this.familyIdentities = familyIdentities;
       this.quarterAllotments = quarterAllotments;
    }
   
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public EmployeeType getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(EmployeeType employeeType) {
        this.employeeType = employeeType;
    }
    public Date getDoj() {
        return this.doj;
    }
    
    public void setDoj(Date doj) {
        this.doj = doj;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getAadharNumber() {
        return this.aadharNumber;
    }
    
    public void setAadharNumber(String aadharNumber) {
        this.aadharNumber = aadharNumber;
    }
    public String getMaritialStatus() {
        return this.maritialStatus;
    }
    
    public void setMaritialStatus(String maritialStatus) {
        this.maritialStatus = maritialStatus;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getQuarterType() {
        return this.quarterType;
    }
    
    public void setQuarterType(String quarterType) {
        this.quarterType = quarterType;
    }
    public String getPerminentAddress() {
        return this.perminentAddress;
    }
    
    public void setPerminentAddress(String perminentAddress) {
        this.perminentAddress = perminentAddress;
    }
    public String getSelfContactNumber() {
        return this.selfContactNumber;
    }
    
    public void setSelfContactNumber(String selfContactNumber) {
        this.selfContactNumber = selfContactNumber;
    }
    public String getEmergencyContactNumber() {
        return this.emergencyContactNumber;
    }
    
    public void setEmergencyContactNumber(String emergencyContactNumber) {
        this.emergencyContactNumber = emergencyContactNumber;
    }
    public String getOtEligibility() {
        return this.otEligibility;
    }
    
    public void setOtEligibility(String otEligibility) {
        this.otEligibility = otEligibility;
    }
    public String getProofType() {
        return this.proofType;
    }
    
    public void setProofType(String proofType) {
        this.proofType = proofType;
    }
    public String getProofNumber() {
        return this.proofNumber;
    }
    
    public void setProofNumber(String proofNumber) {
        this.proofNumber = proofNumber;
    }
    public byte[] getProofScannedCopy() {
        return this.proofScannedCopy;
    }
    
    public void setProofScannedCopy(byte[] proofScannedCopy) {
        this.proofScannedCopy = proofScannedCopy;
    }
    public String getEmpGrade() {
        return this.empGrade;
    }
    
    public void setEmpGrade(String empGrade) {
        this.empGrade = empGrade;
    }
    public Date getRecordCreationDate() {
        return this.recordCreationDate;
    }
    
    public void setRecordCreationDate(Date recordCreationDate) {
        this.recordCreationDate = recordCreationDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getLeaveMasters() {
        return this.leaveMasters;
    }
    
    public void setLeaveMasters(Set leaveMasters) {
        this.leaveMasters = leaveMasters;
    }
    public Set getOvertimes() {
        return this.overtimes;
    }
    
    public void setOvertimes(Set overtimes) {
        this.overtimes = overtimes;
    }
    public Set getGasAllotments() {
        return this.gasAllotments;
    }
    
    public void setGasAllotments(Set gasAllotments) {
        this.gasAllotments = gasAllotments;
    }
    public Set getLoanAllotments() {
        return this.loanAllotments;
    }
    
    public void setLoanAllotments(Set loanAllotments) {
        this.loanAllotments = loanAllotments;
    }
    public Set getIncentiveses() {
        return this.incentiveses;
    }
    
    public void setIncentiveses(Set incentiveses) {
        this.incentiveses = incentiveses;
    }
    public Set getWageses() {
        return this.wageses;
    }
    
    public void setWageses(Set wageses) {
        this.wageses = wageses;
    }
    public Set getDeductionMasters() {
        return this.deductionMasters;
    }
    
    public void setDeductionMasters(Set deductionMasters) {
        this.deductionMasters = deductionMasters;
    }
    public Set getFamilyIdentities() {
        return this.familyIdentities;
    }
    
    public void setFamilyIdentities(Set familyIdentities) {
        this.familyIdentities = familyIdentities;
    }
    public Set getQuarterAllotments() {
        return this.quarterAllotments;
    }
    
    public void setQuarterAllotments(Set quarterAllotments) {
        this.quarterAllotments = quarterAllotments;
    }




}


