package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeType generated by hbm2java
 */
public class EmployeeType  implements java.io.Serializable {


     private int empTypeId;
     private String description;
     private Set employeeProfiles = new HashSet(0);

    public EmployeeType() {
    }

	
    public EmployeeType(int empTypeId) {
        this.empTypeId = empTypeId;
    }
    public EmployeeType(int empTypeId, String description, Set employeeProfiles) {
       this.empTypeId = empTypeId;
       this.description = description;
       this.employeeProfiles = employeeProfiles;
    }
   
    public int getEmpTypeId() {
        return this.empTypeId;
    }
    
    public void setEmpTypeId(int empTypeId) {
        this.empTypeId = empTypeId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getEmployeeProfiles() {
        return this.employeeProfiles;
    }
    
    public void setEmployeeProfiles(Set employeeProfiles) {
        this.employeeProfiles = employeeProfiles;
    }




}


