package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FamilyIdentity generated by hbm2java
 */
public class FamilyIdentity  implements java.io.Serializable {


     private int familyUnitId;
     private EmployeeProfile employeeProfile;
     private Set dependentsInformations = new HashSet(0);
     private Set quarterAllotments = new HashSet(0);
     private Dependents dependents;

    public FamilyIdentity() {
    }

	
    public FamilyIdentity(int familyUnitId, EmployeeProfile employeeProfile) {
        this.familyUnitId = familyUnitId;
        this.employeeProfile = employeeProfile;
    }
    public FamilyIdentity(int familyUnitId, EmployeeProfile employeeProfile, Set dependentsInformations, Set quarterAllotments, Dependents dependents) {
       this.familyUnitId = familyUnitId;
       this.employeeProfile = employeeProfile;
       this.dependentsInformations = dependentsInformations;
       this.quarterAllotments = quarterAllotments;
       this.dependents = dependents;
    }
   
    public int getFamilyUnitId() {
        return this.familyUnitId;
    }
    
    public void setFamilyUnitId(int familyUnitId) {
        this.familyUnitId = familyUnitId;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfile;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfile = employeeProfile;
    }
    public Set getDependentsInformations() {
        return this.dependentsInformations;
    }
    
    public void setDependentsInformations(Set dependentsInformations) {
        this.dependentsInformations = dependentsInformations;
    }
    public Set getQuarterAllotments() {
        return this.quarterAllotments;
    }
    
    public void setQuarterAllotments(Set quarterAllotments) {
        this.quarterAllotments = quarterAllotments;
    }
    public Dependents getDependents() {
        return this.dependents;
    }
    
    public void setDependents(Dependents dependents) {
        this.dependents = dependents;
    }




}


