package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GasConnectionMaster generated by hbm2java
 */
public class GasConnectionMaster  implements java.io.Serializable {


     private int connectionId;
     private String gasCompanyName;
     private Integer gasStoveId;
     private Integer gasConnectionAmount;
     private Integer gasCylinderCount;
     private String gasConnectionHolderName;
     private Date gasConnectionValidateDate;
     private String consumerNumber;
     private Set gasAllotments = new HashSet(0);

    public GasConnectionMaster() {
    }

	
    public GasConnectionMaster(int connectionId) {
        this.connectionId = connectionId;
    }
    public GasConnectionMaster(int connectionId, String gasCompanyName, Integer gasStoveId, Integer gasConnectionAmount, Integer gasCylinderCount, String gasConnectionHolderName, Date gasConnectionValidateDate, String consumerNumber, Set gasAllotments) {
       this.connectionId = connectionId;
       this.gasCompanyName = gasCompanyName;
       this.gasStoveId = gasStoveId;
       this.gasConnectionAmount = gasConnectionAmount;
       this.gasCylinderCount = gasCylinderCount;
       this.gasConnectionHolderName = gasConnectionHolderName;
       this.gasConnectionValidateDate = gasConnectionValidateDate;
       this.consumerNumber = consumerNumber;
       this.gasAllotments = gasAllotments;
    }
   
    public int getConnectionId() {
        return this.connectionId;
    }
    
    public void setConnectionId(int connectionId) {
        this.connectionId = connectionId;
    }
    public String getGasCompanyName() {
        return this.gasCompanyName;
    }
    
    public void setGasCompanyName(String gasCompanyName) {
        this.gasCompanyName = gasCompanyName;
    }
    public Integer getGasStoveId() {
        return this.gasStoveId;
    }
    
    public void setGasStoveId(Integer gasStoveId) {
        this.gasStoveId = gasStoveId;
    }
    public Integer getGasConnectionAmount() {
        return this.gasConnectionAmount;
    }
    
    public void setGasConnectionAmount(Integer gasConnectionAmount) {
        this.gasConnectionAmount = gasConnectionAmount;
    }
    public Integer getGasCylinderCount() {
        return this.gasCylinderCount;
    }
    
    public void setGasCylinderCount(Integer gasCylinderCount) {
        this.gasCylinderCount = gasCylinderCount;
    }
    public String getGasConnectionHolderName() {
        return this.gasConnectionHolderName;
    }
    
    public void setGasConnectionHolderName(String gasConnectionHolderName) {
        this.gasConnectionHolderName = gasConnectionHolderName;
    }
    public Date getGasConnectionValidateDate() {
        return this.gasConnectionValidateDate;
    }
    
    public void setGasConnectionValidateDate(Date gasConnectionValidateDate) {
        this.gasConnectionValidateDate = gasConnectionValidateDate;
    }
    public String getConsumerNumber() {
        return this.consumerNumber;
    }
    
    public void setConsumerNumber(String consumerNumber) {
        this.consumerNumber = consumerNumber;
    }
    public Set getGasAllotments() {
        return this.gasAllotments;
    }
    
    public void setGasAllotments(Set gasAllotments) {
        this.gasAllotments = gasAllotments;
    }




}


