package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Incentives generated by hbm2java
 */
public class Incentives  implements java.io.Serializable {


     private Integer id;
     private EmployeeProfile employeeProfileByEmpiId;
      private Departments deptiId;

    public EmployeeProfile getEmployeeProfileByEmpiId() {
        return employeeProfileByEmpiId;
    }

    public void setEmployeeProfileByEmpiId(EmployeeProfile employeeProfileByEmpiId) {
        this.employeeProfileByEmpiId = employeeProfileByEmpiId;
    }
     private int incentiveId;
     private String incentiveName;
     private String incentiveCode;
     private Integer wage;
     private Integer days;
     private Integer inc;
     private Integer earn;
     private Integer incAmount;
     private Integer grossSalary;
     private Integer netSalary;
     private Date date;

    public Incentives() {
    }

    public Departments getDeptiId() {
        return deptiId;
    }

    public void setDeptiId(Departments deptiId) {
        this.deptiId = deptiId;
    }

	
    public Incentives(int incentiveId) {
        this.incentiveId = incentiveId;
    }
    public Incentives(EmployeeProfile employeeProfile, int incentiveId, String incentiveName, String incentiveCode, Integer wage, Integer days, Integer inc, Integer earn, Integer incAmount, Integer grossSalary, Integer netSalary, Date date) {
       this.employeeProfileByEmpiId = employeeProfile;
       this.incentiveId = incentiveId;
       this.incentiveName = incentiveName;
       this.incentiveCode = incentiveCode;
       this.wage = wage;
       this.days = days;
       this.inc = inc;
       this.earn = earn;
       this.incAmount = incAmount;
       this.grossSalary = grossSalary;
       this.netSalary = netSalary;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfileByEmpiId;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfileByEmpiId = employeeProfile;
    }
    public int getIncentiveId() {
        return this.incentiveId;
    }
    
    public void setIncentiveId(int incentiveId) {
        this.incentiveId = incentiveId;
    }
    public String getIncentiveName() {
        return this.incentiveName;
    }
    
    public void setIncentiveName(String incentiveName) {
        this.incentiveName = incentiveName;
    }
    public String getIncentiveCode() {
        return this.incentiveCode;
    }
    
    public void setIncentiveCode(String incentiveCode) {
        this.incentiveCode = incentiveCode;
    }
    public Integer getWage() {
        return this.wage;
    }
    
    public void setWage(Integer wage) {
        this.wage = wage;
    }
    public Integer getDays() {
        return this.days;
    }
    
    public void setDays(Integer days) {
        this.days = days;
    }
    public Integer getInc() {
        return this.inc;
    }
    
    public void setInc(Integer inc) {
        this.inc = inc;
    }
    public Integer getEarn() {
        return this.earn;
    }
    
    public void setEarn(Integer earn) {
        this.earn = earn;
    }
    public Integer getIncAmount() {
        return this.incAmount;
    }
    
    public void setIncAmount(Integer incAmount) {
        this.incAmount = incAmount;
    }
    public Integer getGrossSalary() {
        return this.grossSalary;
    }
    
    public void setGrossSalary(Integer grossSalary) {
        this.grossSalary = grossSalary;
    }
    public Integer getNetSalary() {
        return this.netSalary;
    }
    
    public void setNetSalary(Integer netSalary) {
        this.netSalary = netSalary;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


