package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1



/**
 * IncentiveRules generated by hbm2java
 */
public class IncentiveRules  implements java.io.Serializable {


     private int incentiveRuleId;
     private String empGrade;
     private Integer flatIncentiveAmount;

    public IncentiveRules() {
    }

	
    public IncentiveRules(int incentiveRuleId) {
        this.incentiveRuleId = incentiveRuleId;
    }
    public IncentiveRules(int incentiveRuleId, String empGrade, Integer flatIncentiveAmount) {
       this.incentiveRuleId = incentiveRuleId;
       this.empGrade = empGrade;
       this.flatIncentiveAmount = flatIncentiveAmount;
    }
   
    public int getIncentiveRuleId() {
        return this.incentiveRuleId;
    }
    
    public void setIncentiveRuleId(int incentiveRuleId) {
        this.incentiveRuleId = incentiveRuleId;
    }
    public String getEmpGrade() {
        return this.empGrade;
    }
    
    public void setEmpGrade(String empGrade) {
        this.empGrade = empGrade;
    }
    public Integer getFlatIncentiveAmount() {
        return this.flatIncentiveAmount;
    }
    
    public void setFlatIncentiveAmount(Integer flatIncentiveAmount) {
        this.flatIncentiveAmount = flatIncentiveAmount;
    }




}


