package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1



/**
 * LeaveMaster generated by hbm2java
 */
public class LeaveMaster  implements java.io.Serializable {


     private int id;
     private EmployeeProfile employeeProfile;
     private Integer leaveTypeId;
     private String empGrade;
     private Integer numberOfDays;
     private Integer excludedDays;

    public LeaveMaster() {
    }

	
    public LeaveMaster(int id) {
        this.id = id;
    }
    public LeaveMaster(int id, EmployeeProfile employeeProfile, Integer leaveTypeId, String empGrade, Integer numberOfDays, Integer excludedDays) {
       this.id = id;
       this.employeeProfile = employeeProfile;
       this.leaveTypeId = leaveTypeId;
       this.empGrade = empGrade;
       this.numberOfDays = numberOfDays;
       this.excludedDays = excludedDays;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfile;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfile = employeeProfile;
    }
    public Integer getLeaveTypeId() {
        return this.leaveTypeId;
    }
    
    public void setLeaveTypeId(Integer leaveTypeId) {
        this.leaveTypeId = leaveTypeId;
    }
    public String getEmpGrade() {
        return this.empGrade;
    }
    
    public void setEmpGrade(String empGrade) {
        this.empGrade = empGrade;
    }
    public Integer getNumberOfDays() {
        return this.numberOfDays;
    }
    
    public void setNumberOfDays(Integer numberOfDays) {
        this.numberOfDays = numberOfDays;
    }
    public Integer getExcludedDays() {
        return this.excludedDays;
    }
    
    public void setExcludedDays(Integer excludedDays) {
        this.excludedDays = excludedDays;
    }




}


