package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1



/**
 * LoanEligibility generated by hbm2java
 */
public class LoanEligibility  implements java.io.Serializable {


     private int eligibilityRuleId;
     private Integer flatAmtRate;

    public LoanEligibility() {
    }

	
    public LoanEligibility(int eligibilityRuleId) {
        this.eligibilityRuleId = eligibilityRuleId;
    }
    public LoanEligibility(int eligibilityRuleId, Integer flatAmtRate) {
       this.eligibilityRuleId = eligibilityRuleId;
       this.flatAmtRate = flatAmtRate;
    }
   
    public int getEligibilityRuleId() {
        return this.eligibilityRuleId;
    }
    
    public void setEligibilityRuleId(int eligibilityRuleId) {
        this.eligibilityRuleId = eligibilityRuleId;
    }
    public Integer getFlatAmtRate() {
        return this.flatAmtRate;
    }
    
    public void setFlatAmtRate(Integer flatAmtRate) {
        this.flatAmtRate = flatAmtRate;
    }




}


