package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LoansMaster generated by hbm2java
 */
public class LoansMaster  implements java.io.Serializable {


     private int loanId;
     private String loanTypeName;
     private String empGrade;
     private Integer eligibilityRuleId;
     private Set loanAllotments = new HashSet(0);

    public LoansMaster() {
    }

	
    public LoansMaster(int loanId) {
        this.loanId = loanId;
    }
    public LoansMaster(int loanId, String loanTypeName, String empGrade, Integer eligibilityRuleId, Set loanAllotments) {
       this.loanId = loanId;
       this.loanTypeName = loanTypeName;
       this.empGrade = empGrade;
       this.eligibilityRuleId = eligibilityRuleId;
       this.loanAllotments = loanAllotments;
    }
   
    public int getLoanId() {
        return this.loanId;
    }
    
    public void setLoanId(int loanId) {
        this.loanId = loanId;
    }
    public String getLoanTypeName() {
        return this.loanTypeName;
    }
    
    public void setLoanTypeName(String loanTypeName) {
        this.loanTypeName = loanTypeName;
    }
    public String getEmpGrade() {
        return this.empGrade;
    }
    
    public void setEmpGrade(String empGrade) {
        this.empGrade = empGrade;
    }
    public Integer getEligibilityRuleId() {
        return this.eligibilityRuleId;
    }
    
    public void setEligibilityRuleId(Integer eligibilityRuleId) {
        this.eligibilityRuleId = eligibilityRuleId;
    }
    public Set getLoanAllotments() {
        return this.loanAllotments;
    }
    
    public void setLoanAllotments(Set loanAllotments) {
        this.loanAllotments = loanAllotments;
    }




}


