package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1



/**
 * OtPayoutSchedule generated by hbm2java
 */
public class OtPayoutSchedule  implements java.io.Serializable {


     private Integer id;
     private WageDefinitions wageDefinitions;
     private Integer payoutDays;

    public OtPayoutSchedule() {
    }

	
    public OtPayoutSchedule(WageDefinitions wageDefinitions) {
        this.wageDefinitions = wageDefinitions;
    }
    public OtPayoutSchedule(WageDefinitions wageDefinitions, Integer payoutDays) {
       this.wageDefinitions = wageDefinitions;
       this.payoutDays = payoutDays;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public WageDefinitions getWageDefinitions() {
        return this.wageDefinitions;
    }
    
    public void setWageDefinitions(WageDefinitions wageDefinitions) {
        this.wageDefinitions = wageDefinitions;
    }
    public Integer getPayoutDays() {
        return this.payoutDays;
    }
    
    public void setPayoutDays(Integer payoutDays) {
        this.payoutDays = payoutDays;
    }




}


