package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Overtime generated by hbm2java
 */
public class Overtime  implements java.io.Serializable {


     private Integer id;
     private EmployeeProfile employeeProfile;
     private String ot;
     private Integer otrate;
     private Date effectiveDate;
     private Integer wageId;

    public Overtime() {
    }

    public Overtime(EmployeeProfile employeeProfile, String ot, Integer otrate, Date effectiveDate, Integer wageId) {
       this.employeeProfile = employeeProfile;
       this.ot = ot;
       this.otrate = otrate;
       this.effectiveDate = effectiveDate;
       this.wageId = wageId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfile;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfile = employeeProfile;
    }
    public String getOt() {
        return this.ot;
    }
    
    public void setOt(String ot) {
        this.ot = ot;
    }
    public Integer getOtrate() {
        return this.otrate;
    }
    
    public void setOtrate(Integer otrate) {
        this.otrate = otrate;
    }
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    public Integer getWageId() {
        return this.wageId;
    }
    
    public void setWageId(Integer wageId) {
        this.wageId = wageId;
    }




}


