package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * QuarterAllotment generated by hbm2java
 */
public class QuarterAllotment  implements java.io.Serializable {


     private Integer id;
     private EmployeeProfile employeeProfile;
     private FamilyIdentity familyIdentity;
     private ResidentialQuarters residentialQuarters;
     private String alloted;
     private Date checkInDate;
     private Date checkOutDate;

    public QuarterAllotment() {
    }

    public QuarterAllotment(EmployeeProfile employeeProfile, FamilyIdentity familyIdentity, ResidentialQuarters residentialQuarters, String alloted, Date checkInDate, Date checkOutDate) {
       this.employeeProfile = employeeProfile;
       this.familyIdentity = familyIdentity;
       this.residentialQuarters = residentialQuarters;
       this.alloted = alloted;
       this.checkInDate = checkInDate;
       this.checkOutDate = checkOutDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfile;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfile = employeeProfile;
    }
    public FamilyIdentity getFamilyIdentity() {
        return this.familyIdentity;
    }
    
    public void setFamilyIdentity(FamilyIdentity familyIdentity) {
        this.familyIdentity = familyIdentity;
    }
    public ResidentialQuarters getResidentialQuarters() {
        return this.residentialQuarters;
    }
    
    public void setResidentialQuarters(ResidentialQuarters residentialQuarters) {
        this.residentialQuarters = residentialQuarters;
    }
    public String getAlloted() {
        return this.alloted;
    }
    
    public void setAlloted(String alloted) {
        this.alloted = alloted;
    }
    public Date getCheckInDate() {
        return this.checkInDate;
    }
    
    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }
    public Date getCheckOutDate() {
        return this.checkOutDate;
    }
    
    public void setCheckOutDate(Date checkOutDate) {
        this.checkOutDate = checkOutDate;
    }




}


