package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ResidentialQuarters generated by hbm2java
 */
public class ResidentialQuarters  implements java.io.Serializable {


     private int quarterId;
     private String quarterType;
     private String quarterCode;
     private Set quarterAllotments = new HashSet(0);

    public ResidentialQuarters() {
    }

	
    public ResidentialQuarters(int quarterId) {
        this.quarterId = quarterId;
    }
    public ResidentialQuarters(int quarterId, String quarterType, String quarterCode, Set quarterAllotments) {
       this.quarterId = quarterId;
       this.quarterType = quarterType;
       this.quarterCode = quarterCode;
       this.quarterAllotments = quarterAllotments;
    }
   
    public int getQuarterId() {
        return this.quarterId;
    }
    
    public void setQuarterId(int quarterId) {
        this.quarterId = quarterId;
    }
    public String getQuarterType() {
        return this.quarterType;
    }
    
    public void setQuarterType(String quarterType) {
        this.quarterType = quarterType;
    }
    public String getQuarterCode() {
        return this.quarterCode;
    }
    
    public void setQuarterCode(String quarterCode) {
        this.quarterCode = quarterCode;
    }
    public Set getQuarterAllotments() {
        return this.quarterAllotments;
    }
    
    public void setQuarterAllotments(Set quarterAllotments) {
        this.quarterAllotments = quarterAllotments;
    }




}


