package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1



/**
 * UserRolls generated by hbm2java
 */
public class UserRolls  implements java.io.Serializable {


     private int rollId;

    public UserRolls() {
    }

    public UserRolls(int rollId) {
       this.rollId = rollId;
    }
   
    public int getRollId() {
        return this.rollId;
    }
    
    public void setRollId(int rollId) {
        this.rollId = rollId;
    }




}


