package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WageDefinitions generated by hbm2java
 */
public class WageDefinitions  implements java.io.Serializable {


     private int wageId;
     private String empType;
     private String wageCalculation;
     private Set wageses = new HashSet(0);
     private Set otPayoutSchedules = new HashSet(0);

    public WageDefinitions() {
    }

	
    public WageDefinitions(int wageId) {
        this.wageId = wageId;
    }
    public WageDefinitions(int wageId, String empType, String wageCalculation, Set wageses, Set otPayoutSchedules) {
       this.wageId = wageId;
       this.empType = empType;
       this.wageCalculation = wageCalculation;
       this.wageses = wageses;
       this.otPayoutSchedules = otPayoutSchedules;
    }
   
    public int getWageId() {
        return this.wageId;
    }
    
    public void setWageId(int wageId) {
        this.wageId = wageId;
    }
    public String getEmpType() {
        return this.empType;
    }
    
    public void setEmpType(String empType) {
        this.empType = empType;
    }
    public String getWageCalculation() {
        return this.wageCalculation;
    }
    
    public void setWageCalculation(String wageCalculation) {
        this.wageCalculation = wageCalculation;
    }
    public Set getWageses() {
        return this.wageses;
    }
    
    public void setWageses(Set wageses) {
        this.wageses = wageses;
    }
    public Set getOtPayoutSchedules() {
        return this.otPayoutSchedules;
    }
    
    public void setOtPayoutSchedules(Set otPayoutSchedules) {
        this.otPayoutSchedules = otPayoutSchedules;
    }




}


