package com.hrms.model;
// Generated Dec 16, 2016 10:52:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wages generated by hbm2java
 */
public class Wages  implements java.io.Serializable {


     private Integer id;
     private EmployeeProfile employeeProfile;
     private WageDefinitions wageDefinitions;
     private Integer basicRate;
     private Date effectiveDate;

    public Wages() {
    }

	
    public Wages(WageDefinitions wageDefinitions) {
        this.wageDefinitions = wageDefinitions;
    }
    public Wages(EmployeeProfile employeeProfile, WageDefinitions wageDefinitions, Integer basicRate, Date effectiveDate) {
       this.employeeProfile = employeeProfile;
       this.wageDefinitions = wageDefinitions;
       this.basicRate = basicRate;
       this.effectiveDate = effectiveDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EmployeeProfile getEmployeeProfile() {
        return this.employeeProfile;
    }
    
    public void setEmployeeProfile(EmployeeProfile employeeProfile) {
        this.employeeProfile = employeeProfile;
    }
    public WageDefinitions getWageDefinitions() {
        return this.wageDefinitions;
    }
    
    public void setWageDefinitions(WageDefinitions wageDefinitions) {
        this.wageDefinitions = wageDefinitions;
    }
    public Integer getBasicRate() {
        return this.basicRate;
    }
    
    public void setBasicRate(Integer basicRate) {
        this.basicRate = basicRate;
    }
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }




}


